# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1beNYX7nTeSwnT3nTT7IFZyzvSlbBtqMv
"""

import kagglehub

path = kagglehub.dataset_download("nehalbirla/vehicle-dataset-from-cardekho")
print("Path to dataset files:", path)

import os

os.listdir(path)

!pip install xgboost streamlit

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

import pickle

import pandas as pd

df = pd.read_csv(path + "/car data.csv")
df.head()

df.info()
df.describe()

df.isnull().sum()

df.dropna(inplace=True)

df.drop("Car_Name", axis=1, inplace=True)

le = LabelEncoder()

df["Fuel_Type"] = le.fit_transform(df["Fuel_Type"])
df["Seller_Type"] = le.fit_transform(df["Seller_Type"])
df["Transmission"] = le.fit_transform(df["Transmission"])

df["Car_Age"] = 2025 - df["Year"]
df.drop("Year", axis=1, inplace=True)

Q1 = df["Selling_Price"].quantile(0.25)
Q3 = df["Selling_Price"].quantile(0.75)
IQR = Q3 - Q1

df = df[(df["Selling_Price"] >= Q1 - 1.5*IQR) &
        (df["Selling_Price"] <= Q3 + 1.5*IQR)]

sns.histplot(df["Selling_Price"], kde=True)
plt.title("Car Price Distribution")
plt.show()

sns.scatterplot(x="Kms_Driven", y="Selling_Price", data=df)
plt.title("Price vs Kilometers Driven")
plt.show()

sns.scatterplot(x="Kms_Driven", y="Selling_Price", data=df)
plt.title("Price vs Kilometers Driven")
plt.show()

plt.figure(figsize=(8,6))
sns.heatmap(df.corr(), annot=True, cmap="coolwarm")
plt.title("Feature Correlation Heatmap")
plt.show()

X = df.drop("Selling_Price", axis=1)
y = df["Selling_Price"]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

lr = LinearRegression()
lr.fit(X_train, y_train)
lr_pred = lr.predict(X_test)

rf = RandomForestRegressor(n_estimators=200, random_state=42)
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)

def evaluate(y_test, y_pred, model_name):
    print(f"\n{model_name}")
    print("R2 Score:", r2_score(y_test, y_pred))
    print("MAE:", mean_absolute_error(y_test, y_pred))
    print("MSE:", mean_squared_error(y_test, y_pred))
    print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

evaluate(y_test, lr_pred, "Linear Regression")
evaluate(y_test, rf_pred, "Random Forest Regressor")

pickle.dump(rf, open("car_price_model.pkl", "wb"))
pickle.dump(scaler, open("scaler.pkl", "wb"))

def predict_price(kms, fuel, seller, trans, owner, age):
    model = pickle.load(open("car_price_model.pkl", "rb"))
    scaler = pickle.load(open("scaler.pkl", "rb"))

    data = scaler.transform([[kms, fuel, seller, trans, owner, age]])
    price = model.predict(data)[0]
    return price

from google.colab import files
files.download("car_price_model.pkl")
files.download("scaler.pkl")

import streamlit as st
import pickle
import numpy as np

model = pickle.load(open("car_price_model.pkl", "rb"))
scaler = pickle.load(open("scaler.pkl", "rb"))

st.title("🚗 Car Price Predictor")

kms = st.number_input("Kilometers Driven")
fuel = st.selectbox("Fuel Type", ["Petrol", "Diesel", "CNG"])
seller = st.selectbox("Seller Type", ["Dealer", "Individual"])
trans = st.selectbox("Transmission", ["Manual", "Automatic"])
owner = st.selectbox("Owner", [0,1,2,3])
age = st.number_input("Car Age")

fuel = 2 if fuel=="Petrol" else 1 if fuel=="Diesel" else 0
seller = 0 if seller=="Dealer" else 1
trans = 0 if trans=="Manual" else 1

if st.button("Predict Price"):
    data = scaler.transform([[kms, fuel, seller, trans, owner, age]])
    price = model.predict(data)[0]
    st.success(f"Estimated Price: ₹ {round(price*100000,2)}")